steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/story-api:$COMMIT_SHA
      - .

images:
  - gcr.io/$PROJECT_ID/story-api:$COMMIT_SHA

# Required in some org policies when a build service account is specified.
options:
  logging: CLOUD_LOGGING_ONLY


